[workspace]
resolver = "3"
members = ["protocol", "rpc", "wallet"]
# Old experimental code, to be removed from project:
exclude = ["adaptor", "bdktest"]

[workspace.dependencies]
anyhow = "1.0.98"
bdk_bitcoind_rpc = "0.20.0"
bdk_electrum = { version = "0.23.0", default-features = false, features = ["use-rustls-ring"] }
bdk_wallet = { version = "2.0.0", features = ["rusqlite"]}
musig2 = { version = "0.3.1", features = ["rand"] }
rand = "0.9.2"
rand_chacha = "0.9.0"
