[package]
name = "wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { workspace = true }
bdk_electrum = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }